#!/bin/sh -eux

PUNTER=${1:-./dist/build/punter/punter}


SETUP=$(echo '427:{"punter":0,"punters":2,"map":{"sites":[{"id":4},{"id":1},{"id":3},{"id":6},{"id":5},{"id":0},{"id":7},{"id":2}],"rivers":[{"source":3,"target":4},{"source":0,"target":1},{"source":2,"target":3},{"source":1,"target":3},{"source":5,"target":6},{"source":4,"target":5},{"source":3,"target":5},{"source":6,"target":7},{"source":5,"target":7},{"source":1,"target":7},{"source":0,"target":7},{"source":1,"target":2}],"mines":[1,5]}}' | $PUNTER)

if [ ! "$SETUP" = '{"state":"state"}' ]; then
  echo "Setup failure"
  exit 1
fi

MOVE=$(echo '64:{"move":{"moves":[{"pass":{"punter":0}},{"pass":{"punter":1}}]}}' | $PUNTER)

if [ ! "$MOVE" = '{"state":"state"}' ]; then
  echo "Move failure"
  exit 1
fi

echo '33:{"stop":{"moves":[],"scores":[]}}' | $PUNTER
echo '122:{"stop":{"moves":[{"claim":{"punter":0,"source":5,"target":7}},{"claim":{"punter":1,"source":7,"target":1}}],"scores":[]}}' | $PUNTER
echo '55:{"stop":{"moves":[],"scores":[{"punter":0,"score":6}]}}' | $PUNTER
echo '167:{"stop":{"moves":[{"claim":{"punter":0,"source":5,"target":7}},{"claim":{"punter":1,"source":7,"target":1}}],"scores":[{"punter":0,"score":6},{"punter":1,"score":6}]}}' | $PUNTER
