#!/bin/sh -eu

PUNTER=${1:-./dist/build/punter/punter}
SERVER=${2:-./dist/build/server/server}

ROOT=$(dirname "$0")/../../..
ROOT=$(cd "$ROOT" > /dev/null 2>&1 && pwd)
TMP=${ROOT}/tmp
TEST=${TMP}/test/$$
mkdir -p ${TEST}

cleanup () {
    rm -rf "${TEST}"
}

trap cleanup SIGHUP SIGINT SIGQUIT SIGTERM

echo "== charles vs charles =="
$SERVER random $PUNTER charles charles

echo "== charles vs tyrion =="
$SERVER random $PUNTER charles lion

echo "== charles vs random =="
$SERVER random $PUNTER charles random

echo "== cersei vs tyrion =="
$SERVER random $PUNTER witch lion

echo "== cersei vs silver =="
$SERVER random $PUNTER witch silver

echo "== silver vs silver =="
$SERVER random $PUNTER silver silver
