#!/bin/sh -eu

PUNTER=${1:-./dist/build/punter/punter}
SERVER=${2:-./dist/build/server/server}

ROOT=$(dirname "$0")/../../..
ROOT=$(cd "$ROOT" > /dev/null 2>&1 && pwd)
TMP=${ROOT}/tmp
TEST=${TMP}/test/$$
mkdir -p ${TEST}

cleanup () {
    rm -rf "${TEST}"
}

trap cleanup SIGHUP SIGINT SIGQUIT SIGTERM

echo "== silver vs silver =="
$SERVER random $PUNTER silver silver

echo "== silver vs silver =="
$SERVER lambda $PUNTER silver silver

echo "== silver vs silver =="
$SERVER circle $PUNTER silver silver
