#!/bin/sh -eu

PUNTER=${1:-./dist/build/punter/punter}
SERVER=${2:-./dist/build/server/server}

ROOT=$(dirname "$0")/../../..
ROOT=$(cd "$ROOT" > /dev/null 2>&1 && pwd)
TMP=${ROOT}/tmp
TEST=${TMP}/test/$$
mkdir -p ${TEST}

cleanup () {
    rm -rf "${TEST}"
}

trap cleanup SIGHUP SIGINT SIGQUIT SIGTERM

CHARLES=$TEST/charles
LANNISTER=$TEST/lannister
CERSEI=$TEST/cersei
TYRION=$TEST/tyrion
SILVER=$TEST/silver
RANDOMX=$TEST/random
IBIS=$TEST/ibis

cat > $CHARLES <<EOF
#!/bin/sh -eu
$PUNTER --charles
EOF

cat > $LANNISTER <<EOF
#!/bin/sh -eu
$PUNTER --lannister
EOF

cat > $CERSEI <<EOF
#!/bin/sh -eu
$PUNTER --cersei
EOF

cat > $TYRION <<EOF
#!/bin/sh -eu
$PUNTER --tyrion
EOF

cat > $SILVER <<EOF
#!/bin/sh -eu
$PUNTER --silver
EOF

cat > $RANDOMX <<EOF
#!/bin/sh -eu
$PUNTER --random
EOF

cat > $IBIS <<EOF
#!/bin/sh -eu
$PUNTER --ibis
EOF

chmod +x $CHARLES $LANNISTER $CERSEI $TYRION $SILVER $RANDOMX $IBIS

echo "== default vs default =="
$SERVER $PUNTER $PUNTER

echo "== charles vs charles =="
$SERVER $CHARLES $CHARLES

echo "== charles vs lannister =="
$SERVER $CHARLES $LANNISTER

echo "== charles vs random =="
$SERVER $CHARLES $RANDOMX

echo "== lannister vs lannister =="
$SERVER $LANNISTER $LANNISTER

echo "== cersei vs tyrion =="
$SERVER $CERSEI $TYRION

echo "== cersei vs silver =="
$SERVER $CERSEI $SILVER

echo "== lannister vs random =="
$SERVER $LANNISTER $RANDOMX

echo "== lannister v ibis =="
for x in {0..5}; do
  echo $IBIS
  echo $LANNISTER
done > $TEST/inputs

$SERVER $(cat $TEST/inputs)
